# This is a basic workflow to help you get started with Actions

name: Issue Branch

on: [issues]

jobs:
    create_issue_branch_job:
        runs-on: ubuntu-latest
        steps:
        - name: Create Issue Branch
          uses: robvanderleek/create-issue-branch@master
          with:
            branchName: tiny
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
