# This is a basic workflow to help you get started with Actions

name: Issue Branch

on: [issues]

jobs:
    create_issue_branch_job:
        runs-on: ubuntu-latest
        steps:
        - name: Create Issue Branch
          id: Create_Issue_Branch
          uses: robvanderleek/create-issue-branch@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - name: Echo branch name
          run: echo ${{ steps.Create_Issue_Branch.outputs.branchName }}
