name: master build

on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
       - name: Setup dotnet
         uses: actions/setup-dotnet@v1
         with:
            dotnet-version: '3.1.x'
       - name: Install dependencies
         working-directory: ./ActionApp
         run: | 
          ls -l
          dotnet restore
       - name: Build
         run: | 
          ls -l
          dotnet build --configuration Release --no-restore
       - name: Test
         run: dotnet test --no-restore --verbosity normal
