name: master build

on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
       - name: Setup dotnet
         uses: actions/setup-dotnet@v1
         with:
            dotnet-version: '3.1.x'
       - name: Install dependencies
         working-directory: ./ActionApp
         run: dotnet restore
       - name: Build
         working-directory: ./ActionApp
         run: dotnet build --configuration Release --no-restore
       - name: Test
         working-directory: ./ActionApp
         run: dotnet test --no-restore --verbosity normal
       - name: Test failed
         if: ${{ failure() }}
         run: echo 'Failed'
